import './globals.scss';
import './styles/header.scss';
import './styles/introduction.scss';
import './styles/featuredProjects.scss';
import './styles/categories.scss';
import './styles/ourStory.scss';
import './styles/footer.scss';

export const metadata = {
    title: 'Aura Living',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>{children}</body>
        </html>
    );
}
